sudo: false
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
before_install:
 - npm install -g npm@latest
install:
 - npm install -g codecov
env:
- NODE_ENV=test
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov